"""
KOE POC Backend Server

Flask server that integrates with the React KOE form app.
Handles:
- API endpoints for form data (GET/POST)
- Catenda webhook handling
- PDF upload to Catenda (PDF generated by React app)
- Data persistence in CSV files

Run with: python server.py
Requires: flask, flask-cors, requests
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
from datetime import datetime
import json
import os
import base64

from database import CSVDatabase
from catenda_integration import CatendaAPI

app = Flask(__name__)
CORS(app)  # Enable CORS for React app

# Initialize components
db = CSVDatabase()
catenda = CatendaAPI()

# Configuration
DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
os.makedirs(DATA_DIR, exist_ok=True)

# =============================================================================
# Health & Status Endpoints
# =============================================================================

@app.route('/api/health', methods=['GET'])
def health_check():
    """Health check endpoint for React app connectivity test"""
    return jsonify({
        'status': 'ok',
        'timestamp': datetime.now().isoformat(),
        'version': '1.0.0'
    })

@app.route('/api/status', methods=['GET'])
def status():
    """Detailed status including Catenda connectivity"""
    catenda_status = catenda.check_connection()
    return jsonify({
        'status': 'ok',
        'database': 'connected',
        'catenda': 'connected' if catenda_status else 'disconnected',
        'cases_count': db.get_cases_count(),
        'timestamp': datetime.now().isoformat()
    })

# =============================================================================
# Case Data Endpoints (for React app)
# =============================================================================

@app.route('/api/cases/<sak_id>', methods=['GET'])
def get_case(sak_id):
    """
    Get case data by sakId
    Used by React app when loading form from URL parameters
    """
    modus = request.args.get('modus', 'koe')

    try:
        case_data = db.get_case(sak_id)
        if not case_data:
            return jsonify({
                'success': False,
                'error': f'Sak {sak_id} ikke funnet'
            }), 404

        return jsonify({
            'success': True,
            'data': {
                'sakId': sak_id,
                'topicGuid': case_data.get('topic_guid', ''),
                'formData': case_data.get('form_data', {}),
                'status': case_data.get('status', ''),
                'createdAt': case_data.get('created_at', ''),
                'updatedAt': case_data.get('updated_at', '')
            }
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/api/varsel-submit', methods=['POST'])
def submit_varsel():
    """
    Handle varsel (warning) submission from entrepreneur
    First step in the KOE workflow
    """
    try:
        data = request.json
        form_data = data.get('formData', {})
        topic_guid = data.get('topicGuid')

        # Generate sakId if not provided
        sak_id = _generate_sak_id('VARSEL')

        # Save to database
        db.save_case(sak_id, {
            'topic_guid': topic_guid,
            'form_data': form_data,
            'status': 'varsel_sendt',
            'modus': 'varsel',
            'created_at': datetime.now().isoformat(),
            'updated_at': datetime.now().isoformat()
        })

        # Log to history
        db.log_history(sak_id, 'varsel_sendt', 'Varsel sendt av entreprenør')

        # Post comment to Catenda if topic_guid exists
        if topic_guid and catenda.is_connected():
            koe_url = _generate_form_url(sak_id, 'koe')
            comment = f"""Varsel mottatt og registrert.

Sak-ID: {sak_id}
Dato: {datetime.now().strftime('%d.%m.%Y %H:%M')}

Entreprenør kan nå sende krav om endringsordre:
{koe_url}"""
            catenda.post_comment(topic_guid, comment)

        return jsonify({
            'success': True,
            'data': {
                'sakId': sak_id,
                'topicGuid': topic_guid,
                'status': 'varsel_sendt',
                'message': f'Varsel registrert med sak-ID: {sak_id}'
            }
        })

    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/api/koe-submit', methods=['POST'])
def submit_koe():
    """
    Handle KOE (claim) submission from entrepreneur
    """
    try:
        data = request.json
        form_data = data.get('formData', {})
        topic_guid = data.get('topicGuid')
        existing_sak_id = data.get('sakId')

        # Use existing sakId or generate new one
        sak_id = existing_sak_id or _generate_sak_id('KOE')

        # Get revision number
        koe_revisjoner = form_data.get('koe_revisjoner', [])
        revision_nr = len(koe_revisjoner) - 1 if koe_revisjoner else 0

        # Save to database
        db.save_case(sak_id, {
            'topic_guid': topic_guid,
            'form_data': form_data,
            'status': 'krav_sendt',
            'modus': 'koe',
            'revision': revision_nr,
            'created_at': db.get_case(sak_id).get('created_at', datetime.now().isoformat()) if db.get_case(sak_id) else datetime.now().isoformat(),
            'updated_at': datetime.now().isoformat()
        })

        # Log to history
        db.log_history(sak_id, 'krav_sendt', f'Krav om endringsordre sendt (rev {revision_nr})')

        # Post comment to Catenda
        if topic_guid and catenda.is_connected():
            svar_url = _generate_form_url(sak_id, 'svar')
            comment = f"""Krav om endringsordre mottatt.

Sak-ID: {sak_id}
Revisjon: {revision_nr}
Dato: {datetime.now().strftime('%d.%m.%Y %H:%M')}

Byggherre kan svare på kravet her:
{svar_url}"""
            catenda.post_comment(topic_guid, comment)

        return jsonify({
            'success': True,
            'data': {
                'sakId': sak_id,
                'topicGuid': topic_guid,
                'status': 'krav_sendt',
                'message': f'Krav registrert - Sak-ID: {sak_id}, Revisjon: {revision_nr}'
            }
        })

    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/api/svar-submit', methods=['POST'])
def submit_svar():
    """
    Handle svar (response) submission from byggherre
    """
    try:
        data = request.json
        form_data = data.get('formData', {})
        sak_id = data.get('sakId')

        if not sak_id:
            return jsonify({
                'success': False,
                'error': 'sakId er påkrevd'
            }), 400

        # Get existing case
        existing_case = db.get_case(sak_id)
        if not existing_case:
            return jsonify({
                'success': False,
                'error': f'Sak {sak_id} ikke funnet'
            }), 404

        topic_guid = existing_case.get('topic_guid')

        # Determine response status based on BH answers
        bh_svar_revisjoner = form_data.get('bh_svar_revisjoner', [])
        latest_svar = bh_svar_revisjoner[-1] if bh_svar_revisjoner else {}
        svar_status = latest_svar.get('status', '')

        # Map status to descriptive text
        status_map = {
            '100000004': 'godkjent',
            '300000002': 'delvis_godkjent',
            '100000010': 'avslaatt_for_sent',
            '100000006': 'avslaatt_uenig',
            '100000003': 'krever_avklaring'
        }
        status_text = status_map.get(svar_status, 'besvart')

        # Update case
        db.save_case(sak_id, {
            **existing_case,
            'form_data': form_data,
            'status': f'svar_{status_text}',
            'modus': 'svar',
            'updated_at': datetime.now().isoformat()
        })

        # Log to history
        revision_nr = len(bh_svar_revisjoner) - 1
        db.log_history(sak_id, f'svar_{status_text}', f'Byggherre har svart (rev {revision_nr}): {status_text}')

        # Post comment to Catenda
        if topic_guid and catenda.is_connected():
            # Determine next action based on status
            if status_text in ['avslaatt_for_sent', 'avslaatt_uenig', 'krever_avklaring']:
                revidering_url = _generate_form_url(sak_id, 'revidering')
                comment = f"""Byggherre har svart på kravet.

Status: {status_text.replace('_', ' ').title()}
Dato: {datetime.now().strftime('%d.%m.%Y %H:%M')}

Entreprenør kan sende revidert krav her:
{revidering_url}"""
            else:
                comment = f"""Byggherre har svart på kravet.

Status: {status_text.replace('_', ' ').title()}
Dato: {datetime.now().strftime('%d.%m.%Y %H:%M')}

Saken er behandlet."""

            catenda.post_comment(topic_guid, comment)

        return jsonify({
            'success': True,
            'data': {
                'sakId': sak_id,
                'topicGuid': topic_guid,
                'status': f'svar_{status_text}',
                'message': f'Svar registrert - Status: {status_text}'
            }
        })

    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@app.route('/api/cases/<sak_id>/revidering', methods=['POST'])
def submit_revidering(sak_id):
    """
    Handle revidering (revision) submission from entrepreneur
    """
    try:
        data = request.json
        form_data = data.get('formData', {})

        # Get existing case
        existing_case = db.get_case(sak_id)
        if not existing_case:
            return jsonify({
                'success': False,
                'error': f'Sak {sak_id} ikke funnet'
            }), 404

        topic_guid = existing_case.get('topic_guid')

        # Get revision number
        koe_revisjoner = form_data.get('koe_revisjoner', [])
        revision_nr = len(koe_revisjoner) - 1 if koe_revisjoner else 0

        # Update case
        db.save_case(sak_id, {
            **existing_case,
            'form_data': form_data,
            'status': 'revidering_sendt',
            'modus': 'revidering',
            'revision': revision_nr,
            'updated_at': datetime.now().isoformat()
        })

        # Log to history
        db.log_history(sak_id, 'revidering_sendt', f'Revidert krav sendt (rev {revision_nr})')

        # Post comment to Catenda
        if topic_guid and catenda.is_connected():
            svar_url = _generate_form_url(sak_id, 'svar')
            comment = f"""Revidert krav om endringsordre mottatt.

Sak-ID: {sak_id}
Revisjon: {revision_nr}
Dato: {datetime.now().strftime('%d.%m.%Y %H:%M')}

Byggherre kan svare på det reviderte kravet her:
{svar_url}"""
            catenda.post_comment(topic_guid, comment)

        return jsonify({
            'success': True,
            'data': {
                'sakId': sak_id,
                'topicGuid': topic_guid,
                'status': 'revidering_sendt',
                'message': f'Revidert krav registrert - Revisjon: {revision_nr}'
            }
        })

    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

# =============================================================================
# PDF Upload Endpoint (receives PDF from React app)
# =============================================================================

@app.route('/api/cases/<sak_id>/pdf', methods=['POST'])
def upload_pdf(sak_id):
    """
    Receive PDF generated by React app and upload to Catenda

    Expected request body:
    {
        "pdfBase64": "base64-encoded PDF data",
        "filename": "KOE-2023-001.pdf"
    }
    """
    try:
        data = request.json
        pdf_base64 = data.get('pdfBase64')
        filename = data.get('filename', f'{sak_id}.pdf')

        if not pdf_base64:
            return jsonify({
                'success': False,
                'error': 'pdfBase64 er påkrevd'
            }), 400

        # Get case for topic_guid
        case_data = db.get_case(sak_id)
        if not case_data:
            return jsonify({
                'success': False,
                'error': f'Sak {sak_id} ikke funnet'
            }), 404

        topic_guid = case_data.get('topic_guid')

        # Decode PDF
        pdf_bytes = base64.b64decode(pdf_base64)

        # Save locally (backup)
        pdf_path = os.path.join(DATA_DIR, 'pdfs', filename)
        os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
        with open(pdf_path, 'wb') as f:
            f.write(pdf_bytes)

        # Upload to Catenda if connected
        document_guid = None
        if topic_guid and catenda.is_connected():
            document_guid = catenda.upload_document(
                topic_guid=topic_guid,
                filename=filename,
                file_content=pdf_bytes
            )

        # Log to history
        db.log_history(sak_id, 'pdf_uploaded', f'PDF lastet opp: {filename}')

        return jsonify({
            'success': True,
            'data': {
                'sakId': sak_id,
                'filename': filename,
                'documentGuid': document_guid,
                'localPath': pdf_path,
                'message': 'PDF lastet opp' + (' til Catenda' if document_guid else ' lokalt')
            }
        })

    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

# =============================================================================
# Attachment Upload
# =============================================================================

@app.route('/api/cases/<sak_id>/attachments', methods=['POST'])
def upload_attachment(sak_id):
    """
    Handle file attachment uploads
    """
    try:
        if 'file' not in request.files:
            return jsonify({
                'success': False,
                'error': 'Ingen fil mottatt'
            }), 400

        file = request.files['file']
        category = request.form.get('category', 'general')

        if file.filename == '':
            return jsonify({
                'success': False,
                'error': 'Ingen fil valgt'
            }), 400

        # Save file
        attachment_dir = os.path.join(DATA_DIR, 'attachments', sak_id)
        os.makedirs(attachment_dir, exist_ok=True)

        filename = file.filename
        filepath = os.path.join(attachment_dir, filename)
        file.save(filepath)

        # Log
        db.log_history(sak_id, 'attachment_uploaded', f'Vedlegg lastet opp: {filename} ({category})')

        return jsonify({
            'success': True,
            'data': {
                'attachmentId': f'{sak_id}_{filename}',
                'filename': filename,
                'url': f'/api/attachments/{sak_id}/{filename}',
                'uploadedAt': datetime.now().isoformat()
            }
        })

    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

# =============================================================================
# Draft Saving
# =============================================================================

@app.route('/api/cases/<sak_id>/draft', methods=['PUT'])
@app.route('/api/drafts', methods=['PUT'])
def save_draft(sak_id=None):
    """
    Save form draft for later continuation
    """
    try:
        data = request.json
        form_data = data.get('formData', {})

        if not sak_id:
            sak_id = _generate_sak_id('DRAFT')

        # Save draft
        draft_path = os.path.join(DATA_DIR, 'drafts', f'{sak_id}.json')
        os.makedirs(os.path.dirname(draft_path), exist_ok=True)

        with open(draft_path, 'w', encoding='utf-8') as f:
            json.dump({
                'sak_id': sak_id,
                'form_data': form_data,
                'saved_at': datetime.now().isoformat()
            }, f, ensure_ascii=False, indent=2)

        return jsonify({
            'success': True,
            'data': {
                'sakId': sak_id
            }
        })

    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

# =============================================================================
# Catenda Webhook Handler
# =============================================================================

@app.route('/webhook/catenda', methods=['POST'])
def handle_webhook():
    """
    Handle incoming webhooks from Catenda

    Triggers:
    - topic.created: New topic created, generate form link
    - comment.added: Comment added, check for status updates
    """
    try:
        payload = request.json
        event_type = payload.get('event_type', '')

        if event_type == 'topic.created':
            return _handle_topic_created(payload)
        elif event_type == 'comment.added':
            return _handle_comment_added(payload)
        else:
            return jsonify({'status': 'ignored', 'reason': f'Unknown event type: {event_type}'})

    except Exception as e:
        return jsonify({
            'status': 'error',
            'error': str(e)
        }), 500

def _handle_topic_created(payload):
    """Handle new topic creation from Catenda"""
    topic_data = payload.get('data', {})
    topic_guid = topic_data.get('guid')
    title = topic_data.get('title', 'Ukjent')
    author = topic_data.get('author', 'Ukjent')

    # Generate sakId
    sak_id = _generate_sak_id('KOE')

    # Create initial case record
    db.save_case(sak_id, {
        'topic_guid': topic_guid,
        'form_data': {
            'sak': {
                'sak_id_display': sak_id,
                'sakstittel': title,
                'opprettet_av': author,
                'opprettet_dato': datetime.now().strftime('%Y-%m-%d')
            }
        },
        'status': 'opprettet',
        'modus': 'initial',
        'created_at': datetime.now().isoformat(),
        'updated_at': datetime.now().isoformat()
    })

    # Log
    db.log_history(sak_id, 'topic_created', f'Sak opprettet fra Catenda topic: {topic_guid}')

    # Post form link to Catenda
    if catenda.is_connected():
        varsel_url = _generate_form_url(sak_id, 'varsel')
        comment = f"""Sak registrert i KOE-systemet.

Sak-ID: {sak_id}
Tittel: {title}
Opprettet: {datetime.now().strftime('%d.%m.%Y %H:%M')}

Start med å fylle ut varsel:
{varsel_url}"""
        catenda.post_comment(topic_guid, comment)

    return jsonify({
        'status': 'ok',
        'sakId': sak_id,
        'message': 'Topic registered and form link posted'
    })

def _handle_comment_added(payload):
    """Handle comment added to existing topic"""
    comment_data = payload.get('data', {})
    topic_guid = comment_data.get('topic_guid')
    comment_text = comment_data.get('text', '').lower()

    # Find case by topic_guid
    case = db.get_case_by_topic(topic_guid)
    if not case:
        return jsonify({'status': 'ignored', 'reason': 'Topic not found in database'})

    # Check for status keywords (simple pattern matching)
    # This can be expanded based on requirements

    return jsonify({
        'status': 'ok',
        'message': 'Comment processed'
    })

# =============================================================================
# Helper Functions
# =============================================================================

def _generate_sak_id(prefix='KOE'):
    """Generate unique case ID"""
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    return f'{prefix}-{timestamp}'

def _generate_form_url(sak_id, modus):
    """Generate URL for React form app"""
    # This should be configured based on deployment
    base_url = os.environ.get('REACT_APP_URL', 'https://khjohns.github.io/Skjema_Endringsmeldinger')
    return f'{base_url}/?sakId={sak_id}&modus={modus}'

# =============================================================================
# Main
# =============================================================================

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    debug = os.environ.get('FLASK_DEBUG', 'true').lower() == 'true'

    print(f"""
    ╔════════════════════════════════════════════╗
    ║     KOE POC Backend Server                 ║
    ╠════════════════════════════════════════════╣
    ║  Port: {port}                                ║
    ║  Debug: {debug}                              ║
    ║  Data dir: {DATA_DIR}              ║
    ╚════════════════════════════════════════════╝

    Endpoints:
    - GET  /api/health
    - GET  /api/cases/<sakId>
    - POST /api/varsel-submit
    - POST /api/koe-submit
    - POST /api/svar-submit
    - POST /api/cases/<sakId>/revidering
    - POST /api/cases/<sakId>/pdf
    - POST /webhook/catenda
    """)

    app.run(host='0.0.0.0', port=port, debug=debug)
